[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["nextest", "run"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.ci-test]
dependencies = [
    "build",
    "test"
]

[tasks.check-all]
dependencies = [
    "format",
    "lint",
    "build",
    "test"
]
